[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "rankfit"
version = "0.1.0"
description = "Segment-level ranking quality metrics for machine learning models"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Emma Chung", email = "hsiaoyin.chung@gmail.com"},
]
maintainers = [
    {name = "Emma Chung", email = "hsiaoyin.chung@gmail.com"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]


[project.urls]
"Homepage" = "github.com/EMMA-CHUNG/rankfit"
"Bug Reports" = "github.com/EMMA-CHUNG/rankfit/issues"
"Source" = "github.com/EMMA-CHUNG/rankfit"
"Documentation" = "https://github.com/EMMA-CHUNG/rankfit#readme"


[tool.setuptools]
packages = ["rankfit"]

[tool.black]
line-length = 100
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"